/**
 * @fileoverview gRPC-Web generated client stub for messenger
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.23.3
// source: proto/messenger/v1/messenger_v1.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_messenger_v1_messenger_v1_pb from '../../../proto/messenger/v1/messenger_v1_pb';


export class MessengerServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStreamEnvelopes = new grpcWeb.MethodDescriptor(
    '/messenger.MessengerService/StreamEnvelopes',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_messenger_v1_messenger_v1_pb.Conversation,
    proto_messenger_v1_messenger_v1_pb.Envelope,
    (request: proto_messenger_v1_messenger_v1_pb.Conversation) => {
      return request.serializeBinary();
    },
    proto_messenger_v1_messenger_v1_pb.Envelope.deserializeBinary
  );

  streamEnvelopes(
    request: proto_messenger_v1_messenger_v1_pb.Conversation,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_messenger_v1_messenger_v1_pb.Envelope> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/messenger.MessengerService/StreamEnvelopes',
      request,
      metadata || {},
      this.methodDescriptorStreamEnvelopes);
  }

}

